updated naming in README and addding the arxiv manuscript
Probe-Particle/ppafm pull request #271
Opened 2024-03-16 12:30 UTC by ondrejkrejci

Fixes: #266 
On top of that the arxiv manuscript is mentioned.

2024-03-18 08:19 UTC, NikoOinonen requested changes
One typo, otherwise looks good.

2024-03-18 08:19 UTC, NikoOinonen commented on README.md
> +* **complex_tip** - Modification of the Probe-Particle <odel with 2 particles allows a better fit to experimental results at the cost of additional fitting parameters.
```suggestion
* **complex_tip** - Modification of the Probe-Particle model with 2 particles allows a better fit to experimental results at the cost of additional fitting parameters.
```

2024-03-18 08:33 UTC, ProkopHapala approved these changes

2024-03-18 10:50 UTC, yakutovicha requested changes
Thanks, @ondrejkrejci. Here is my 50 cents

2024-03-18 10:50 UTC, yakutovicha commented on README.md
> +The python package is named as `ppafm`.
```suggestion
The Python package is named as `ppafm`.
```

2024-03-18 10:50 UTC, yakutovicha commented on README.md
> +Simple and efficient **simulation software for high-resolution atomic force microscopy** (**HR-AFM**) and other scanning probe microscopy (SPM) techniques with sub-molecular resolution (STM, IETS, TE
```suggestion
Simple and efficient simulation software for high-resolution atomic force microscopy (HR-AFM) and other scanning probe microscopy (SPM) techniques with sub-molecular resolution (STM, IETS, TERS).
```

I feel there is too much bold text in the readme. Feels a bit messy to me.

2024-03-18 10:50 UTC, yakutovicha commented on README.md
> +It simulates deflection of the particle attached to the tip (typically CO molecule, but also e.g. Xe, Cl-, H2O and others).
```suggestion
It simulates the deflection of the probe particle attached to the tip (typically CO molecule, but also e.g. Xe, Cl-, H2O and others).
```

maybe we should mention the "probe particle" here?

2024-04-08 09:35 UTC, yakutovicha commented
@ondrejkrejci would you be able to address those issues before tomorrow's meeting? Thanks!

2024-04-08 10:10 UTC, ondrejkrejci commented
Don't know, let's see


From: Aliaksandr Yakutovich ***@***.***>
Sent: Monday, April 8, 2024 12:35 PM
To: Probe-Particle/ppafm ***@***.***>
Cc: Krejci Ondrej ***@***.***>; Mention ***@***.***>
Subject: Re: [Probe-Particle/ppafm] updated naming in README and addding the arxiv manuscript (PR #271)


@ondrejkrejci<https://github.com/ondrejkrejci> would you be able to address those issues before tomorrow's meeting? Thanks!

-
Reply to this email directly, view it on GitHub<https://github.com/Probe-Particle/ppafm/pull/271#issuecomment-2042295742>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADFZAFPRCMRBMJUWXSZDJNLY4JQFTAVCNFSM6AAAAABEZJAT7KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBSGI4TKNZUGI>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-04-09 07:54 UTC, ondrejkrejci commented
Ok, I have managed :-)

2024-04-09 11:01 UTC, NikoOinonen approved these changes

2024-04-09 11:27 UTC, yakutovicha approved these changes

2024-04-09 11:27 UTC, merged